name: my_words_note
description: A personal knowledge management app for translators and interpreters
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0

  # State Management
  provider: ^6.1.1

  # UUID Generation
  uuid: ^4.3.3

  # File Operations
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  share_plus: ^7.2.1

  # CSV/JSON Processing
  csv: ^6.0.0

  # UI
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
